AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda + API Gateway using SAM

Resources:
  PlaylistAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: PlaylistAPI
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        AllowOrigins:
          - http://localhost:5173
          - https://main.d37vhm5bmnvd3f.amplifyapp.com

  # Read Playlist
  ReadPlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReadPlaylistFunction
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: Read/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tune_out
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /readPlaylist
            Method: GET
            ApiId: !Ref PlaylistAPI

  # Delete Playlist
  DeletePlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeletePlaylistFunction
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: Delete/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tune_out
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /DeletePlaylist
            Method: DELETE
            ApiId: !Ref PlaylistAPI

    #Create Playlist
  CreatePlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreatePlaylistFunction
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: Create/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tune_out
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /CreatePlaylist
            Method: POST
            ApiId: !Ref PlaylistAPI

  # Update Playlist
  UpdatePlaylistFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: UpdatePlaylistFunction
        Handler: index.handler
        Runtime: nodejs22.x
        CodeUri: Update/
        Policies:
          - DynamoDBCrudPolicy:
              TableName: tune_out
        Events:
          ApiForMyApp:
            Type: HttpApi
            Properties:
              Path: /UpdatePlaylist
              Method: POST
              ApiId: !Ref PlaylistAPI


Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${PlaylistAPI}.execute-api.${AWS::Region}.amazonaws.com"